In [1]:
[[1,0,0],
 [0,1,2]]

[[1, 0, 0], [0, 1, 2]]

In [2]:
from numpy import *

In [3]:
a = arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [9]:
a.itemsize

8

In [10]:
b = array([6,7,8])

In [11]:
b

array([6, 7, 8])

In [12]:
b.dtype

dtype('int64')

Printing Arrays

In [13]:
a = arange(6)

In [14]:
a

array([0, 1, 2, 3, 4, 5])

In [15]:
b = arange(12).reshape(4,3)

In [16]:
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Basic Operations

In [17]:
a = array( [20,30,40,50] )

In [18]:
b = arange( 4 )

In [19]:
b

array([0, 1, 2, 3])

In [20]:
c = a - b
c

array([20, 29, 38, 47])

In [21]:
b**2

array([0, 1, 4, 9])

In [22]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [23]:
A = array( [[1,1],
            [0,1]] )
B = array( [[2,0],
            [3,4]] )

In [25]:
A*B

array([[2, 0],
       [0, 4]])

In [27]:
a = ones(3, dtype=int32)
a

array([1, 1, 1], dtype=int32)

In [29]:
b = linspace(0,pi,4)
b

array([ 0.        ,  1.04719755,  2.0943951 ,  3.14159265])

In [30]:
c = exp(c*1j)
c

array([ 0.40808206+0.91294525j, -0.74805753-0.66363388j,
        0.95507364+0.29636858j, -0.99233547+0.12357312j])

In [33]:
c.dtype.name

'complex128'

Multidimensional arrays

In [32]:
def f(x,y):
    return 10*x+y

In [35]:
b = fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [36]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [37]:
for row in b:
    print row

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [40]:
for element in b.flat:
    print element

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


Shape Manipulation